# Generated by Django 5.2.5 on 2025-09-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
