# Generated by Django 5.2.5 on 2025-09-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_gift_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='price',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='meal_preference',
        ),
    ]
